drop table if exists Taco_Order CASCADE;
drop table if exists ingredient;
drop table if exists ingredient_ref;
drop table if exists USERS;



create table if not exists Taco_Order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_Name   varchar(50) not null,
    delivery_Street varchar(50) not null,
    delivery_City   varchar(50) not null,
    delivery_State  varchar(2)  not null,
    delivery_Zip    varchar(10) not null,
    cc_number       varchar(16) not null,
    cc_expiration   varchar(5)  not null,
    cc_cvv          varchar(3)  not null,
    placed_at       timestamp   not null
);

create table if not exists Taco
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           varchar(50) not null,
    taco_order     bigint      not null,
    taco_order_key bigint      not null,
    created_at     timestamp   not null
);

create table if not exists Ingredient
(
    id   varchar(4)  not null,
    name varchar(25) not null,
    type varchar(10) not null
);

create table if not exists Ingredient_Ref
(
    ingredient varchar(4) not null,
    taco       bigint     not null,
    taco_key   bigint     not null
);

create table if not exists USERS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar,
    password    varchar,
    fullname    varchar,
    street      varchar,
    city        varchar,
    state       varchar,
    zip         varchar,
    phoneNumber varchar
);

alter table Taco
    add foreign key (taco_order) references Taco_Order (id);

