drop table if exists Taco_Order CASCADE;
drop table if exists Ingredient cascade ;
drop table if exists Taco_Ingredients cascade ;
drop table if exists USERS cascade ;
drop table if exists Taco CASCADE ;
drop table if exists Taco_Order_Tacos cascade ;

create table if not exists Ingredient
(
    id   varchar(4)  not null unique ,
    name varchar(25) not null,
    type varchar(10) not null
);

create table if not exists Taco
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      varchar(50) not null,
    created_at timestamp   not null
);

create table if not exists Taco_Ingredients
(
    taco_id       bigint     not null,
    ingredients_id varchar(4) not null
);

alter table Taco_Ingredients
    add foreign key (taco_id) references Taco (id);
alter table Taco_Ingredients
    add foreign key (ingredients_id) references Ingredient (id);

create table if not exists Taco_Order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deliveryName   varchar(50) not null,
    deliveryStreet varchar(50) not null,
    deliveryCity   varchar(50) not null,
    deliveryState  varchar(2)  not null,
    deliveryZip    varchar(10) not null,
    ccNumber       varchar(16) not null,
    ccExpiration   varchar(5)  not null,
    ccCVV          varchar(3)  not null,
    placedAt       timestamp   not null
);

create table if not exists Taco_Order_Tacos
(
    tacoOrder bigint not null,
    taco      bigint not null
);

alter table Taco_Order_Tacos
    add foreign key (tacoOrder) references Taco_Order (id);
alter table Taco_Order_Tacos
    add foreign key (taco) references Taco (id);

